In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('MagicBricks.csv')

In [3]:
data

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0
...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0

In [4]:
data.head()

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0

In [5]:
data.isna().sum()

Area             0
BHK              0
Bathroom         2
Furnishing       5
Locality         0
Parking         33
Price            0
Status           0
Transaction      0
Type             5
Per_Sqft       241
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Area         1259 non-null   float64
 1   BHK          1259 non-null   int64
 2   Bathroom     1257 non-null   float64
 3   Furnishing   1254 non-null   object
 4   Locality     1259 non-null   object
 5   Parking      1226 non-null   float64
 6   Price        1259 non-null   int64
 7   Status       1259 non-null   object
 8   Transaction  1259 non-null   object
 9   Type         1254 non-null   object
 10  Per_Sqft     1018 non-null   float64
dtypes: float64(4), int64(2), object(5)
memory usage: 108.3+ KB

In [7]:
data['Per_Sqft']

0           NaN
1        6667.0
2        6667.0
3        6667.0
4        6667.0
         ...
1254    12916.0
1255    12916.0
1256    12916.0
1257    12916.0
1258    12916.0
Name: Per_Sqft, Length: 1259, dtype: float64

In [8]:
data['Per_Sqft'].isna()

0        True
1       False
2       False
3       False
4       False
        ...
1254    False
1255    False
1256    False
1257    False
1258    False
Name: Per_Sqft, Length: 1259, dtype: bool

In [9]:
data.loc[data['Per_Sqft'].isna()]

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
30,1500.0,1,NaN,Unfurnished,Lajpat Nagar 2,NaN,13500000,Ready_to_move,Resale,Apartment,NaN
31,800.0,2,2.0,Unfurnished,Lajpat Nagar 1,1.0,15000000,Ready_to_move,New_Property,Builder_Floor,NaN
32,900.0,2,2.0,Unfurnished,Lajpat Nagar,1.0,10500000,Ready_to_move,New_Property,Builder_Floor,NaN
33,1080.0,3,2.0,Semi-Furnished,"Vikram Vihar, Lajpat Nagar",1.0,22500000,Ready_to_move,New_Property,Builder_Floor,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1185,900.0,2,2.0,Unfurnished,Kalkaji,2.0,15000000,Ready_to_move,Resale,Apartment,NaN
1199,2520.0,3,3.0,Unfurnished,Hauz Khas,NaN,47500000,Ready_to_move,New_Property,Builder_Floor,NaN
1200,1700.0,3,4.0,Unfurnished,Hauz Khas,2.0,45000000,Ready_to_move,New_Property,Builder_Floor,NaN
1229,2097.0,3,3.0,Unfurnished,Chittaranjan Park,NaN,29000000,Ready_to_move,Resale,Builder_Floor,NaN
1230,1250.0,3,3.0,Semi-Furnished,"Arya Chittaranjan Park, Chittaranjan Park",1.0,25500000,Almost_ready,New_Property,Builder_Floor,NaN

In [10]:
data.loc[data['Per_Sqft'].isna(),:]

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
30,1500.0,1,NaN,Unfurnished,Lajpat Nagar 2,NaN,13500000,Ready_to_move,Resale,Apartment,NaN
31,800.0,2,2.0,Unfurnished,Lajpat Nagar 1,1.0,15000000,Ready_to_move,New_Property,Builder_Floor,NaN
32,900.0,2,2.0,Unfurnished,Lajpat Nagar,1.0,10500000,Ready_to_move,New_Property,Builder_Floor,NaN
33,1080.0,3,2.0,Semi-Furnished,"Vikram Vihar, Lajpat Nagar",1.0,22500000,Ready_to_move,New_Property,Builder_Floor,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1185,900.0,2,2.0,Unfurnished,Kalkaji,2.0,15000000,Ready_to_move,Resale,Apartment,NaN
1199,2520.0,3,3.0,Unfurnished,Hauz Khas,NaN,47500000,Ready_to_move,New_Property,Builder_Floor,NaN
1200,1700.0,3,4.0,Unfurnished,Hauz Khas,2.0,45000000,Ready_to_move,New_Property,Builder_Floor,NaN
1229,2097.0,3,3.0,Unfurnished,Chittaranjan Park,NaN,29000000,Ready_to_move,Resale,Builder_Floor,NaN
1230,1250.0,3,3.0,Semi-Furnished,"Arya Chittaranjan Park, Chittaranjan Park",1.0,25500000,Almost_ready,New_Property,Builder_Floor,NaN

In [11]:
data.loc[data['Per_Sqft'].isna(),:].index

Int64Index([   0,   30,   31,   32,   33,   34,   35,   36,   37,   38,
            ...
            1180, 1181, 1182, 1183, 1184, 1185, 1199, 1200, 1229, 1230],
           dtype='int64', length=241)

In [12]:
missing_target_rows = data.loc[data['Per_Sqft'].isna(),:].index

In [13]:
missing_target_rows

Int64Index([   0,   30,   31,   32,   33,   34,   35,   36,   37,   38,
            ...
            1180, 1181, 1182, 1183, 1184, 1185, 1199, 1200, 1229, 1230],
           dtype='int64', length=241)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [99]:
def preprocessing_inputs(df,target='Price'):
    df = df.copy()
    missing_target_rows = df.loc[df['Per_Sqft'].isna(),:].index
    df = df.drop(missing_target_rows,axis = 0).reset_index(drop =True)
    
    # fill na value 
    df['Parking'] =df['Parking'].fillna(df['Parking'].mean())
    df['Bathroom'] =df['Bathroom'].fillna(df.Bathroom.mean())
    #df['Per_Sqft'] = df['Per_Sqft'].fillna(df['Per_Sqft'].mean())
    # fill na value binary object columns
    for column in ['Furnishing','Type']:
        df[column] = df[column].fillna(df[column].mode()[0])
    # binary encoding columns
   
   
  
    # one hot encode
    df = pd.get_dummies(df,drop_first = True)
    
    # split data 
    if target=='Per_Sqft':
        df = df.drop(['Price'],axis = 'columns')
        y = df['Per_Sqft'] 
        X = df.drop(['Per_Sqft'],axis = 'columns')
    elif target=='Price':
        df = df.drop(['Per_Sqft'],axis = 'columns')
        y = df['Price']
        X = df.drop(['Price'],axis = 'columns')
    # train test split
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,shuffle =True,random_state = 1)
    # scaling data
    scaler.fit(X_train)
    X_train = pd.DataFrame(scaler.transform(X_train),index = X_train.index,columns = X_train.columns)
    X_test  = pd.DataFrame(scaler.transform(X_test),index = X_test.index,columns = X_test.columns)
    return X_train,X_test,y_train,y_test

In [100]:
X_train,X_test,y_train,y_test =preprocessing_inputs(data,target = 'Price')

In [101]:
X_train

,Area,BHK,Bathroom,Parking,Status,Transaction,Type,Furnishing_Semi-Furnished,Furnishing_Unfurnished,"Locality_Abhimanyu Apartments, Vasundhara Enclave",...,"Locality_Vijay Enclave, Mahavir Enclave","Locality_Vijay Vihar, Rohini","Locality_Vikram Vihar, Lajpat Nagar","Locality_Vinoba Puri, Lajpat Nagar","Locality_Virat Residency, Dwarka Mor","Locality_Vishwas Nagar, Shahdara","Locality_Yamuna Apartment, Alaknanda","Locality_Yamuna Vihar, Shahdara","Locality_Zakir Nagar, New Friends Colony","Locality_mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar"
304,-0.463235,3.302528,2.186378,-0.226259,0.250326,-0.806917,-0.897150,-1.100889,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,5.617829,-0.035072,-0.035072
47,-0.182897,0.206646,0.374044,-0.226259,0.250326,-0.806917,1.114641,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
530,0.109123,1.238607,2.186378,0.138234,0.250326,-0.806917,-0.897150,-1.100889,1.519521,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
919,-0.412253,-0.825315,-1.438289,-0.226259,0.250326,-0.806917,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
19,-0.387310,-0.825315,-0.532122,-0.226259,0.250326,-0.806917,1.114641,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,-0.416512,0.206646,-0.532122,-0.226259,0.250326,-0.806917,1.114641,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
72,0.798289,1.238607,2.186378,-0.226259,0.250326,1.239284,-0.897150,-1.100889,1.519521,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
908,0.576354,1.238607,1.280211,0.138234,0.250326,1.239284,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
235,-0.042727,0.206646,0.374044,0.502727,0.250326,1.239284,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
37,-0.007685,0.206646,0.374044,-0.226259,0.250326,-0.806917,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072

In [102]:
X_test

,Area,BHK,Bathroom,Parking,Status,Transaction,Type,Furnishing_Semi-Furnished,Furnishing_Unfurnished,"Locality_Abhimanyu Apartments, Vasundhara Enclave",...,"Locality_Vijay Enclave, Mahavir Enclave","Locality_Vijay Vihar, Rohini","Locality_Vikram Vihar, Lajpat Nagar","Locality_Vinoba Puri, Lajpat Nagar","Locality_Virat Residency, Dwarka Mor","Locality_Vishwas Nagar, Shahdara","Locality_Yamuna Apartment, Alaknanda","Locality_Yamuna Vihar, Shahdara","Locality_Zakir Nagar, New Friends Colony","Locality_mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar"
267,-0.489517,-0.825315,-1.438289,-0.226259,0.250326,-0.806917,1.114641,-1.100889,1.519521,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
142,-0.241301,0.206646,-0.532122,-0.226259,0.250326,1.239284,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
837,-0.307297,-0.825315,-0.532122,-0.226259,0.250326,1.239284,1.114641,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
175,-0.328906,0.206646,-0.532122,-0.226259,0.250326,1.239284,1.114641,-1.100889,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
481,0.634758,1.238607,1.280211,0.502727,0.250326,1.239284,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,-0.299704,-0.825315,-0.532122,-0.226259,0.250326,-0.806917,1.114641,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
274,-0.124493,1.238607,0.374044,-0.226259,0.250326,1.239284,-0.897150,-1.100889,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
968,-0.241301,0.206646,0.374044,0.138234,0.250326,-0.806917,1.114641,-1.100889,1.519521,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
354,-0.457979,-0.825315,-0.532122,-0.226259,0.250326,-0.806917,-0.897150,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072
663,-0.416512,0.206646,0.374044,-0.226259,0.250326,-0.806917,1.114641,0.908357,-0.658102,0.0,...,-0.035072,-0.035072,-0.049629,-0.049629,-0.060821,-0.035072,-0.049629,-0.178005,-0.035072,-0.035072

In [103]:
y_train

304    22000000
47     15500000
530    52500000
919     8000000
19     11000000
         ...
767     9030000
72     46000000
908    80000000
235    26000000
37     31500000
Name: Price, Length: 814, dtype: int64

In [104]:
y_test

267     3300000
142     6200000
837    17000000
175     4370000
481    75000000
         ...
560    10700000
274    11500000
968    18500000
354     4800000
663     4500000
Name: Price, Length: 204, dtype: int64

In [105]:
from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC,LinearSVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [106]:
models = {
    'Logistic_Rgression'   : LogisticRegression(),
    'Linear_Rgression'     : LinearRegression(),
    'Ridge'                : Ridge(),
    'Lasso'                : Lasso(),
    'svc'                  : SVC(),
    'Linear_svc'           : LinearSVC(),
    'Decision_tree'        : DecisionTreeClassifier(),
    'Random_forest'        : RandomForestClassifier(),
    'Gradient_Boosting'    : GradientBoostingClassifier(),
    'Neural_Network'       : MLPClassifier(),
    'K_Neighbors'          : KNeighborsClassifier(),
     'GNB'                 : GaussianNB()
}
for name, model in models.items():
    model.fit(X_train,y_train)
    print(name + 'Trannied')

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic_RgressionTrannied
Linear_RgressionTrannied
RidgeTrannied

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.5708842936163572e+16, tolerance: 64049889784127.76
  model = cd_fast.enet_coordinate_descent(

LassoTrannied
svcTrannied

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

Linear_svcTrannied
Decision_treeTrannied
Random_forestTrannied
Gradient_BoostingTrannied
Neural_NetworkTrannied
K_NeighborsTrannied
GNBTrannied

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [107]:
X_train.isna().sum()

Area                                                                                                                                                                                                                                                                                                                                               0
BHK                                                                                                                                                                                                                                                                                                                                                0
Bathroom                                                                                                                                                                                                                                                                                                                                           0
Parking                                                                                                                                                                                                                                                                                                                                            0
Status                                                                                                                                                                                                                                                                                                                                             0
                                                                                                                                                                                                                                                                                                                                                  ..
Locality_Vishwas Nagar, Shahdara                                                                                                                                                                                                                                                                                                                   0
Locality_Yamuna Apartment, Alaknanda                                                                                                                                                                                                                                                                                                               0
Locality_Yamuna Vihar, Shahdara                                                                                                                                                                                                                                                                                                                    0
Locality_Zakir Nagar, New Friends Colony                                                                                                                                                                                                                                                                                                           0
Locality_mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar    0
Length: 319, dtype: int64

In [108]:
for name, model in models.items():
    print(name + ' Accuracy : {:2f}'.format(model.score(X_test,y_test)))

Logistic_Rgression Accuracy : 0.200980
Linear_Rgression Accuracy : -10683679588682301976870912.000000
Ridge Accuracy : 0.717352
Lasso Accuracy : 0.575175
svc Accuracy : 0.132353
Linear_svc Accuracy : 0.176471
Decision_tree Accuracy : 0.176471
Random_forest Accuracy : 0.176471
Gradient_Boosting Accuracy : 0.171569
Neural_Network Accuracy : 0.191176
K_Neighbors Accuracy : 0.058824
GNB Accuracy : 0.137255