In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('abalone_original.csv')

In [4]:
df.head()

,sex,length,diameter,height,whole-weight,shucked-weight,viscera-weight,shell-weight,rings
0,M,91,73,19,102.8,44.9,20.2,30.0,15
1,M,70,53,18,45.1,19.9,9.7,14.0,7
2,F,106,84,27,135.4,51.3,28.3,42.0,9
3,M,88,73,25,103.2,43.1,22.8,31.0,10
4,I,66,51,16,41.0,17.9,7.9,11.0,7

In [5]:
x = df.drop(['shell-weight'],axis = 'columns')

In [6]:
y = df['shell-weight']

In [7]:
x.head()

,sex,length,diameter,height,whole-weight,shucked-weight,viscera-weight,rings
0,M,91,73,19,102.8,44.9,20.2,15
1,M,70,53,18,45.1,19.9,9.7,7
2,F,106,84,27,135.4,51.3,28.3,9
3,M,88,73,25,103.2,43.1,22.8,10
4,I,66,51,16,41.0,17.9,7.9,7

In [8]:
y

0       30.0
1       14.0
2       42.0
3       31.0
4       11.0
        ...
4172    49.8
4173    52.1
4174    61.6
4175    59.2
4176    99.0
Name: shell-weight, Length: 4177, dtype: float64

In [11]:
x = pd.get_dummies(x,drop_first = True)

In [12]:
x

,length,diameter,height,whole-weight,shucked-weight,viscera-weight,rings,sex_I,sex_M
0,91,73,19,102.8,44.9,20.2,15,0,1
1,70,53,18,45.1,19.9,9.7,7,0,1
2,106,84,27,135.4,51.3,28.3,9,0,0
3,88,73,25,103.2,43.1,22.8,10,0,1
4,66,51,16,41.0,17.9,7.9,7,1,0
...,...,...,...,...,...,...,...,...,...
4172,113,90,33,177.4,74.0,47.8,11,0,0
4173,118,88,27,193.2,87.8,42.9,10,0,1
4174,120,95,41,235.2,105.1,57.5,9,0,1
4175,125,97,30,218.9,106.2,52.2,10,0,0
4176,142,111,39,389.7,189.1,75.3,12,0,1

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [15]:
X_train

,length,diameter,height,whole-weight,shucked-weight,viscera-weight,rings,sex_I,sex_M
2486,98,80,29,132.7,42.0,25.9,13,0,0
1752,142,112,44,403.0,184.3,90.8,11,0,1
285,107,83,34,175.8,59.0,39.3,10,0,0
1746,140,113,35,371.3,168.9,78.7,10,0,1
1087,90,73,25,92.4,42.7,19.7,8,1,0
...,...,...,...,...,...,...,...,...,...
3373,108,81,31,194.3,64.5,38.8,19,0,1
3597,137,106,34,312.0,129.4,76.6,11,0,1
19,90,64,20,76.2,34.1,15.0,9,0,1
3066,128,100,30,240.3,111.8,46.2,9,0,0
2523,113,88,30,196.6,89.5,47.1,9,0,0

In [16]:
X_test

,length,diameter,height,whole-weight,shucked-weight,viscera-weight,rings,sex_I,sex_M
3365,88,62,23,72.5,26.8,16.4,11,1,0
599,112,89,39,196.2,61.0,44.9,16,0,0
2921,120,90,30,192.5,87.5,44.5,9,0,0
1708,129,100,38,311.9,148.2,74.3,14,0,1
2485,71,52,18,38.5,15.4,7.6,8,1,0
...,...,...,...,...,...,...,...,...,...
3866,105,86,33,143.4,57.8,34.9,10,0,0
3256,115,96,30,174.9,75.0,38.6,12,0,0
979,107,87,28,174.8,74.7,45.8,8,0,1
4163,78,62,17,68.8,36.2,13.9,7,1,0
2977,86,66,20,89.8,50.8,16.5,6,1,0

In [20]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [22]:
reg.fit(X_train,y_train)

LinearRegression()

In [23]:
reg.score(X_test,y_test)

0.9526751878039518

In [24]:
y_pred_reg = reg.predict(X_test)

In [25]:
y_pred_reg

array([ 2.47796997e+01,  6.79486753e+01,  5.22415214e+01,  7.92571409e+01,
        1.31569107e+01, -6.42957215e+00,  2.32630511e+01,  6.87263139e+01,
        3.27483923e+01,  3.22597972e+01,  4.58182608e+00,  9.93995479e+01,
        5.69933050e+01,  6.04697709e+01,  6.41295876e+01,  7.93717798e+01,
        2.35204773e+01,  5.92211606e+01,  2.61798090e+01,  3.50197116e+01,
        3.21854690e+01,  4.63261276e+01,  7.85012029e+01,  5.53543607e+01,
        5.37069639e+01,  5.42801872e+01,  9.34352105e+01,  2.74712149e+01,
        1.26373898e+01,  1.55667232e+01,  6.34849333e+01,  6.92116168e+01,
        1.46769741e+01,  6.80163739e+01,  1.62438929e+01,  4.07004241e+01,
        8.84181214e+00,  3.11042094e+00,  1.14332987e+02,  5.47685955e+01,
        6.02649330e+01,  1.38865654e-01,  6.99513643e+01,  5.79503180e+01,
        5.57369173e+01,  4.70564798e+01,  3.54964084e+01,  1.76133654e+01,
        1.08636383e+01,  6.75649575e+01,  8.16217329e+01,  3.40964288e+01,
        2.67258532e+01,  5.14067927e+01,  5.40836944e+01,  2.92597674e+01,
        7.05940401e+01,  1.10049572e+02,  4.21559975e+01,  2.96260123e+01,
        5.36621542e+01,  7.12428238e+01,  3.12626780e+01,  4.32791320e+01,
        4.36125830e+01,  1.00503599e+02,  6.05918256e+01,  3.18930516e+01,
        1.35298619e+02,  1.87527848e+01,  4.02878314e+01,  6.46009203e+01,
        6.91439246e+01,  8.24313491e+01,  2.59779377e+01,  5.55238485e+01,
        1.68112325e+01,  3.52061631e+01,  5.01777642e+01,  2.98750660e+01,
        3.78905989e+01,  1.27283482e+01,  6.03393081e+01,  5.94770713e+01,
        7.01596582e+01,  7.71679259e+00,  7.83598853e+01,  1.60503406e+01,
        7.41041820e+01,  4.14174387e+00,  6.38271104e+01,  6.70356892e+01,
        1.88292685e+01,  7.22483922e+01,  2.38564722e+01,  3.72741433e+01,
        5.99269266e+01,  3.54296211e+01,  6.92054464e+01,  4.49437228e+00,
        1.75335789e+01,  6.47438866e+01,  1.94882929e+01,  5.64918326e+01,
        6.35576124e+01,  6.53438496e+01,  5.94469582e+01,  2.39505643e+01,
        8.63509084e+01,  1.09251928e+02,  4.88770685e+01,  4.75721918e+01,
        9.78744605e+01,  5.70635840e+01,  5.03765140e+01,  3.48063499e+01,
        8.54346966e+01,  1.72927992e+01,  8.09100037e+01,  9.49565593e+01,
        3.07239368e+01,  6.10600244e+01,  4.25734441e+01,  3.11291879e+01,
        5.08884488e+01,  4.27925359e+01,  6.33233411e+01,  8.21787082e+01,
        9.80309621e+01,  6.07573311e+01,  6.26927948e+01,  6.12161366e+01,
        1.46747947e+01,  1.02536547e+02,  8.88906412e+01,  5.92364214e+01,
        3.34402898e+01,  8.32997099e+01,  6.43147404e+01,  8.57646022e+01,
        5.05044034e+01,  2.92800273e+01,  3.27553991e+01,  2.05348915e+01,
        3.39940372e+01,  4.43266102e+01,  4.54646787e+01,  5.79967448e+00,
        4.57193757e+01,  3.04142945e+01,  6.68041772e+01,  5.61793093e+01,
        5.75145117e+01,  7.55767072e+01,  2.17147188e+01,  3.80733828e+01,
        3.11427984e+01,  4.98996980e+01,  3.17408345e+01,  3.51804985e+01,
        3.69482868e+01,  7.86700669e+01,  3.73756547e+01,  2.48212524e+01,
        1.28968783e+02,  6.76029370e+01,  9.84240589e+01,  4.51996818e+01,
        7.47325327e+01,  7.19855648e+01,  2.17807651e+01,  6.99989522e+00,
        5.11938105e+01,  5.62017756e+01,  3.08179074e+01, -7.34803014e-01,
        8.05908921e+01,  7.62866936e+01,  4.67076581e+01,  5.49384988e+01,
        8.33795670e+00,  2.73030479e+01, -3.41077439e+00,  6.83482053e+01,
        2.99757099e+00,  2.38941015e+01,  6.77801263e+01,  3.27154232e+01,
        2.16382532e+01, -3.25248045e-01,  6.44365271e+01,  3.77355697e+00,
        3.51881054e+01,  5.93240374e+01,  6.38348709e+01,  6.20286495e+01,
        7.82922497e+01,  8.48381752e+00,  7.51419701e+00,  1.35043257e+01,
        6.66545041e+01,  9.53534687e+01,  8.01501111e+01,  4.14137392e+01,
        6.79558047e+01,  2.97189670e+01,  3.90691806e+01,  2.12034882e+01,
        6.46394822e+01,  6.07068619e+01,  6.09080960e+01,  1.60251211e+01,
        3.44083525e+01,  6.18185071e+01,  3.02056395e+01,  2.13990943e+01,
        1.56893965e+01,  1.17671995e+01,  1.48788422e+01,  9.27596700e+01,
        8.00215298e+01,  9.64261557e+01,  4.90504633e+01,  2.86377800e+01,
        5.57309957e+01,  1.09643760e+02,  1.25755652e+02,  3.00924519e+01,
        2.55167720e+01,  6.54652320e+01,  2.65512233e+01,  2.20585006e+01,
        1.57264637e+01,  1.00833210e+02,  4.80703116e+01,  8.72751245e+01,
        3.22373740e+01,  6.68924471e+01,  4.51978041e+01,  6.00152611e+01,
        5.31820885e+01,  1.01710383e+02,  2.32261295e+01,  5.38395743e+01,
        3.17061121e+01,  2.87599734e+01,  1.07160382e+01,  8.04254718e+01,
        6.98389012e+01,  4.50234860e+01,  7.00875710e+00,  3.02880039e+01,
        4.92550647e+01,  1.71355568e+01,  8.08922910e+01,  6.69121929e+01,
        2.56007421e+01, -1.20011018e+00,  1.47489058e+01,  7.32385657e+01,
        3.56640448e+01,  7.02974206e+01,  1.53991617e+01,  3.20509706e+01,
        5.84009066e+01,  2.55553675e+01,  3.38640797e+01,  4.74429304e+00,
        3.96393635e+01,  6.67785449e+01,  5.13617445e+01,  1.07885046e+02,
       -2.30532855e+00,  3.23742967e+01,  2.38283113e+01,  1.56555675e+01,
        2.31746595e+01,  5.39057463e+01,  4.96619458e+01,  4.45543861e+00,
        2.97742921e+01,  3.33674451e+01,  6.53580984e+01,  4.23692985e+01,
        5.48898166e+01,  2.42604185e+01,  6.96510265e+01,  3.98235556e+01,
        3.04346246e+01,  8.16726320e+01,  2.37119286e+01,  2.27969648e+01,
        1.26875065e+01,  7.60868094e+01,  7.87219438e+01,  3.42988317e+01,
        6.07316285e+01,  9.92034460e+01,  4.32770892e+01,  6.18490273e+01,
        1.24945545e+01,  5.82591720e+01,  1.01431819e+02, -3.75899474e-01,
        2.42692011e+01,  5.45552030e+01,  7.60043790e+01,  5.88348176e+01,
        3.03842469e+01,  8.57342109e+01,  4.40173188e+01,  7.10009255e+01,
        1.09235232e+01,  1.86931920e+01,  4.00835371e+01,  1.40245424e+02,
        2.98207493e+01,  5.94031526e+00,  1.37276367e+02,  8.38498957e+01,
        5.69108267e+01,  4.55044604e+01,  3.85915030e+01,  3.85200724e+00,
        9.79745449e+01,  6.81723624e+01, -2.08413964e+00,  5.92679397e+00,
       -7.32753558e-01,  8.92273643e+01,  7.01192431e+01,  5.33109433e+01,
        9.37115774e+01,  2.03447113e+01,  3.09220284e+01,  6.19984111e+01,
        5.18281999e+01,  2.91230200e+01,  1.30189331e+01,  5.14474480e+01,
        7.99176304e+01,  4.75406563e+01,  5.23517640e+01,  8.63253911e+01,
        1.68054040e+00,  5.65841599e+01,  5.89130478e+01,  3.36008486e+01,
        4.92581065e+01,  7.49002140e+01,  7.59384799e+01,  5.92078518e+01,
        7.43889691e+01,  1.00075616e+02,  4.76037176e+01,  1.39461806e+01,
        1.65095231e+00,  2.68540325e+01,  6.30494013e+01,  5.50304919e+01,
        9.90094937e+00,  1.46301893e+01,  4.61966103e+01,  4.24170149e+01,
        4.24553247e+01,  4.88422970e+01,  7.85587629e+01,  8.77082335e+01,
        1.18399768e+01,  1.18703667e+02,  6.30651011e+01,  2.56728310e+01,
        2.83642040e+01,  4.24085300e+01,  1.90872102e+01,  9.06710135e+01,
        6.95773829e+01,  4.51702005e+01,  4.37920198e+01,  1.75569636e+01,
        3.57574681e+01,  6.19658764e+01,  6.59566303e+01,  6.71220200e+01,
        2.80786778e+01,  1.31812110e+01,  9.31370328e-01,  3.54719031e+01,
        9.67306107e+01,  7.62449604e+01,  1.31218504e+01,  4.73319983e+01,
        5.77958212e+01,  3.71954105e+01,  6.37929583e+01,  8.45817987e+01,
        1.47636935e+01,  3.69034100e+01,  6.76988640e+01,  2.14547138e+01,
        4.67071477e+01,  4.91148978e+01,  4.30521001e+01,  5.18309967e+01,
        2.88606230e+01,  6.87609962e+01,  3.94507851e+01,  4.78666834e+01,
        3.68564425e+01,  1.04566859e+02,  9.08378923e+01,  5.25853371e+01,
        2.80886714e+01,  1.60177570e+01,  2.91249669e+01,  2.92001045e+01,
        6.57437946e+01,  7.93863981e+00,  1.54605863e+01,  6.00672752e+01,
        9.77234152e+01,  2.07707106e+01,  4.39079083e+01,  1.68308953e+01,
        4.21802846e+01,  1.06853025e+02,  6.70808697e+01,  6.47592533e+01,
        8.04305522e+01,  2.58543502e+01,  4.59701602e+01,  4.75643258e+01,
        6.66560005e+01,  5.20602164e+01,  1.68018401e+01,  3.99990004e+01,
        4.81842346e+01,  4.85843112e+01,  3.12689124e+01,  2.35364675e+01,
        2.83765900e+01,  8.64703266e+01,  4.18211830e+01,  3.62261789e+01,
        7.06380253e+01,  6.69001417e+01,  7.53271054e+01,  2.98111259e+01,
        4.98367258e+01,  9.91472606e+01,  5.28314325e+01,  5.19854940e+01,
        1.55523336e+01,  4.99873367e+01,  3.58611763e+01,  1.90709167e+01,
        6.35315129e+01,  3.27972196e+01,  4.80056551e+01,  4.89662076e+01,
        1.01762504e+02,  7.59005022e+01,  4.03929409e+01,  6.78155501e+01,
        2.44032016e+01,  3.05306217e+01,  1.12702714e+02,  4.22091802e+01,
        6.64044113e+01,  5.44019685e+01,  6.60940370e+01,  6.85576165e+01,
        3.13730680e+01,  7.02636883e+01,  8.54723589e+01,  5.50823770e+01,
        8.59053787e+01,  1.55157307e+00,  3.73616848e+01,  2.71837340e+00,
        5.56703660e+01,  5.80728233e+01,  6.60964662e+01,  8.16537199e+01,
        5.98325280e+01,  7.86524554e+00,  1.85832358e+01,  4.01114725e+01,
        9.53355204e+01,  1.09167169e+02,  3.34570203e+01,  5.89293912e+01,
        3.94252615e+01,  9.50161916e+01,  2.11184994e+01,  7.73516612e+01,
        5.72483823e+01,  7.61876834e+01,  4.92132773e+01,  4.44228958e+01,
        6.20031250e+01,  1.86247668e+01,  6.24502151e+01,  2.78701084e+01,
        2.15012674e+01, -3.56136790e-01,  3.11188704e+01,  8.84786525e+01,
        4.63460550e+01,  2.53853781e+01,  5.57150770e+01,  8.38911032e+01,
        9.03584146e+01,  8.52473092e+01,  3.03194470e+00,  2.85732006e+01,
        3.34450853e+01,  2.32691381e+01,  6.74708658e+01,  6.41606646e+01,
        6.66258966e+01,  4.00912866e+00,  9.37541032e+00,  3.33309202e+01,
        5.20102230e+01,  4.56139366e+01, -1.66206140e+00,  1.18929622e+01,
        4.48805463e+01,  3.79903946e+01,  2.54797152e+01,  4.47845313e+01,
        2.48881360e+01,  2.34011815e+01,  1.05983134e+01,  1.11712240e+02,
        5.69978147e+01,  7.37463054e+01,  1.64275674e+01,  6.93059507e+01,
        3.02255016e+01,  2.14772024e+01,  5.77059794e+01,  5.01842185e+01,
        2.47287165e+01,  5.98573469e+01,  4.80815771e+01,  3.70754315e+01,
        3.69060748e+01,  4.63844741e+01,  6.12897701e+01,  5.27648739e+01,
        1.03485010e+02,  1.74637087e+01,  2.82121612e+01,  4.60681209e+01,
        7.13881263e+01,  6.56568332e+01,  7.04103825e+01,  2.66815407e+01,
        4.08477224e+01,  3.27158125e+01,  6.16982833e+01,  5.92947199e+01,
        7.14203596e+01,  5.43115495e+01,  2.03769106e+01,  5.81317683e+01,
        3.28525127e+01,  5.35931668e+00,  1.02089045e+02,  3.11116005e+01,
        1.43987824e+02,  9.77792233e+01,  6.86894167e+01,  9.26217030e+00,
        3.10229389e+01,  1.39766967e+01,  3.89561007e+01,  4.43881839e+01,
        5.25997353e+01,  3.87102772e+01,  1.89992603e+01,  7.21356823e+01,
        3.84008316e+00,  5.29438942e+01,  3.33268985e+01,  6.62068056e+01,
        9.25095348e+00,  7.44336337e+01,  3.83514511e+01,  6.29136931e+01,
        6.68328020e+01,  5.30723187e+01,  2.23849132e-01,  6.30549326e+01,
        7.38805150e+01,  5.28566997e+01,  9.72836957e+01,  2.23454554e+01,
        3.47741966e+01,  8.01256117e+01,  2.49306900e+01,  2.52617919e+01,
        3.92395049e+01,  6.01586387e+01,  3.60416507e+01,  7.12054621e+01,
        3.36120245e+01,  5.15622757e+01,  2.98289051e+00,  6.79570880e+01,
        3.78368143e+01,  6.67734584e+00,  1.02939268e+02,  3.77622873e+01,
        7.45636034e+01,  3.96190191e+01,  2.45705241e+01,  1.18033581e+01,
        5.86812792e+01,  3.84138262e+01,  1.17695162e+01,  9.79869883e+01,
        1.95443347e+01,  1.15938321e+01,  4.61241960e+01,  3.39440684e+01,
        5.54551366e+01,  4.75260970e+01,  7.80037956e+01,  2.25978335e+01,
        1.17888042e+01,  2.98916653e+01,  7.41732027e+01,  1.34057920e+01,
        5.09319674e+01,  1.20271142e+01,  8.58041507e+01,  6.50007747e+01,
        2.14563692e+01,  8.94044376e+01,  1.52463195e+01,  2.84995803e+01,
        9.67053939e+01,  5.16803800e+01,  6.52622835e+01,  5.51976064e+01,
        3.94356205e+01,  5.43247943e+01,  5.49560581e+01,  6.06590365e+01,
        3.44726479e+01,  4.68681427e+01,  2.05861557e+01,  3.04524515e+01,
        6.75988776e+01,  5.79735955e+01,  4.99111524e+01,  8.16289394e+01,
        5.17804288e+01,  2.64891467e+01,  2.67518822e+01,  2.78813197e+01,
        1.64110302e+01,  5.73351474e+00,  9.38418804e+00,  1.23747010e+01,
        9.21774978e+01,  7.61044215e+01,  1.12953684e+02,  2.75483053e+01,
        6.87157750e+01,  4.63874795e+01,  3.89430197e+01,  6.37098651e+01,
        6.71657780e+01,  2.89432217e+01,  1.89997543e+01,  5.23443544e+01,
        7.80969559e+01,  9.22612797e+01,  8.45046655e+01,  2.82599399e+01,
        5.92491776e+00,  3.69111388e+01,  4.88876772e+01,  1.07966938e+01,
        5.32651468e+01,  3.15431696e+00,  5.87422434e+01,  3.59808327e+01,
        6.98843687e+01,  6.40764808e+01,  2.96101614e+01,  5.72189252e+01,
        7.10354197e+01,  6.25008189e+01,  1.48165082e-01,  4.54182692e+01,
        1.27146174e+01,  3.40880326e+01,  1.08147165e+02,  8.23818650e+01,
        4.35984347e+01,  7.04571476e+01,  5.70554709e+01,  2.36719612e+01,
        1.61821992e+00,  7.50574405e+01,  1.96672775e+00,  4.70470548e+01,
        8.83511431e+01,  2.88358905e+01,  7.19431387e+01,  4.43928208e+01,
        2.35539931e+01,  2.03731479e+01,  3.71290427e+01,  2.95881967e+01,
        1.30124769e+01,  3.21511188e+01,  5.89142764e+01,  8.32483337e+01,
        3.09197567e+01,  6.38582394e+00,  1.48383670e+02,  1.99879189e+01,
        5.01498845e+01,  2.74891459e+01,  4.85361164e+01,  1.12556444e+02,
        6.47799882e+01,  3.65712413e+01,  4.87475782e+01,  3.10530891e+01,
        2.73141828e+01,  5.30842359e+01,  5.53369562e+01,  5.78375789e+01,
        4.67119764e+01,  5.06842342e+01,  8.49928301e+01,  2.41963825e+01,
        6.91775423e+01,  9.11535811e+01,  7.37114570e+01,  4.76721757e+01,
        2.77667525e+01,  5.54254500e+01,  8.57822927e+01,  4.49774911e+01,
        2.13378081e+01,  9.58190585e+01,  1.65534558e+01,  3.75779234e+01,
        5.54634104e+01,  8.90885862e+01,  1.68586243e+01,  4.14053471e+01,
        4.65403171e+01,  6.28118703e+01,  4.50823056e+01,  1.11586725e+02,
        5.06275128e+01,  4.76067121e+00,  3.56991049e+01,  4.95080544e+01,
        4.31180984e+01,  9.79262314e+01,  6.56059845e+01,  4.04415991e+01,
        3.28709571e+01,  8.62992189e+01,  3.26562283e+01,  6.39466715e+01,
        2.59291159e+01,  7.44373640e+01,  6.85623400e+01,  5.56316258e+01,
        7.97301382e+01,  6.45644604e+00,  1.20678551e+02,  6.11866660e+01,
        3.38369578e+01,  4.31283041e+01,  8.41618363e+01,  2.26542862e+01,
        4.09277003e+01,  8.02983846e+01,  5.50514334e+01,  8.96179202e+01,
        3.51646263e+01,  7.06797287e+01,  3.74263203e+01,  7.20713461e+01,
        8.98876404e+01,  5.26126541e+01,  7.68830402e+01,  4.36345462e+01,
        5.31762578e+01,  1.29106091e+01,  2.73845218e+01,  6.59064589e+01,
        3.35982281e+01,  4.09195819e+01,  2.69503408e+01,  3.35715327e+01,
        4.60861985e+01,  5.60241468e+00,  5.84076765e+01,  2.80814690e+01,
        5.58632991e+01,  5.33993845e+01,  4.86555337e+01,  8.89362508e+01,
        2.49138480e+01,  4.81305700e+01,  2.99474095e+01,  7.91620765e+01,
        5.22770370e+01,  8.05666770e+01,  8.25986703e+01,  3.47081682e+01,
        3.80172957e+01,  5.88754925e+01,  1.14836198e+02,  2.67453744e+01,
        4.17092480e+01,  5.43839351e+01,  5.50475213e+01,  4.41562695e+01,
        5.31201849e+01,  4.76908071e+01,  1.84452113e+01,  2.23250077e+01])

In [31]:
from sklearn.metrics import r2_score,confusion_matrix
r2 = r2_score(y_pred_reg,y_test)

In [32]:
r2

0.9503848553556901