In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('superstoresale.csv')

In [3]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [4]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [6]:
data.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [7]:
data=data.fillna(0)

In [24]:
data['Sub-Category'].nunique()

17

In [8]:
data.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [35]:
def preprocessing_inputs(df):
    df = df.copy()
    #drop unneed columns 
    df = df.drop(['Row ID','Order ID','Customer Name','Product Name','Postal Code'],axis= 'columns')
    # one hot-encode 
    df = pd.get_dummies(df,drop_first = True)
    #split data into X,y
    y = df['Sales']
    X = df.drop(['Sales'],axis = 'columns')
    # data for train 
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

    return X_train,X_test,y_train,y_test

In [36]:
X_train,X_test,y_train,y_test = preprocessing_inputs(data)

In [37]:
X_train.head()

,Order Date_01/02/2015,Order Date_01/02/2017,Order Date_01/03/2015,Order Date_01/03/2016,Order Date_01/03/2017,Order Date_01/04/2015,Order Date_01/04/2017,Order Date_01/04/2018,Order Date_01/05/2016,Order Date_01/05/2017,...,Sub-Category_Envelopes,Sub-Category_Fasteners,Sub-Category_Furnishings,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables
1122,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6868,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7133,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
y_train

1122      22.960
6868    2887.056
8747      30.960
7133      27.460
4699       5.248
          ...
1365     239.952
6286     239.976
8750     133.980
7717       1.938
9510      38.340
Name: Sales, Length: 7840, dtype: float64

In [39]:
X_test

,Order Date_01/02/2015,Order Date_01/02/2017,Order Date_01/03/2015,Order Date_01/03/2016,Order Date_01/03/2017,Order Date_01/04/2015,Order Date_01/04/2017,Order Date_01/04/2018,Order Date_01/05/2016,Order Date_01/05/2017,...,Sub-Category_Envelopes,Sub-Category_Fasteners,Sub-Category_Furnishings,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables
8016,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9752,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4057,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
780,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9638,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [40]:
y_test

8016      60.672
318     3991.980
6390      12.960
9752       2.496
4057     646.200
          ...
8232     169.450
780        4.280
3768    1013.832
9638      11.560
29       124.200
Name: Sales, Length: 1960, dtype: float64

In [41]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [42]:
reg.fit(X_train,y_train)

LinearRegression()

In [43]:
reg.score(X_test,y_test)

-7.469768004754782e+23

In [18]:
from sklearn.linear_model import LogisticRegression
rog = LogisticRegression()

In [34]:
rog.fit(X_train,y_train)

ValueError: Unknown label type: 'continuous'

In [ ]:
rog.score(X_test,y_test)

In [ ]:
from sklearn.svm import SVC 
svm = SVC()

In [ ]:
svm.fit(X_train,y_train)

In [ ]:
svm