In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data  = pd.read_csv('Car_Price.csv')

In [3]:
data

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [4]:
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [5]:
data['Market Category'].nunique()

71

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [7]:
def preprocessing_inputs(df):
    df = df.copy()
    # fill na value
    for column in ['Engine HP','Engine Cylinders'] :
        df[column] = df[column].fillna(df[column].mean())
    # fillna value catagorical column
    df['Engine Fuel Type'] = df['Engine Fuel Type'].fillna(df['Engine Fuel Type'].mode()[0])
   
    df['Number of Doors'] = df['Number of Doors'].fillna(df['Number of Doors'].mean())
    # # fillna catagorical column
    df['Market Category'] = df['Market Category'].fillna(df['Market Category'].mode()[0])
    # data get dummies
    df = pd.get_dummies(df,drop_first = True)
    # split df in X,y
    y = df['MSRP']
    X = df.drop(['MSRP'],axis = 'columns')
    # train model 
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
    return X_train,X_test,y_train,y_test

In [8]:
X_train,X_test,y_train,y_test = preprocessing_inputs(data)

In [9]:
X_train

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,Make_Alfa Romeo,Make_Aston Martin,Make_Audi,...,Vehicle Style_Convertible,Vehicle Style_Convertible SUV,Vehicle Style_Coupe,Vehicle Style_Crew Cab Pickup,Vehicle Style_Extended Cab Pickup,Vehicle Style_Passenger Minivan,Vehicle Style_Passenger Van,Vehicle Style_Regular Cab Pickup,Vehicle Style_Sedan,Vehicle Style_Wagon
10950,2015,381.0,8.0,4.0,17,13,2031,0,0,0,...,0,0,0,0,1,0,0,0,0,0
180,1992,217.0,6.0,2.0,21,15,617,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11472,2017,268.0,4.0,4.0,27,20,640,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1349,2002,140.0,4.0,2.0,30,21,26,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1617,2014,173.0,4.0,4.0,29,21,1851,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1740,2001,150.0,6.0,2.0,19,15,586,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5193,2009,217.0,6.0,2.0,26,17,210,0,0,0,...,1,0,0,0,0,0,0,0,0,0
8153,2008,310.0,8.0,2.0,16,12,1851,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9758,2015,138.0,4.0,4.0,33,25,1385,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8810,1990,105.0,4.0,2.0,25,21,549,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [10]:
y_train

10950    41385
180       2248
11472    30995
1349     19855
1617     20595
         ...
1740     18360
5193     32300
8153     27045
9758     21345
8810      2000
Name: MSRP, Length: 9531, dtype: int64

In [11]:
X_test

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,Make_Alfa Romeo,Make_Aston Martin,Make_Audi,...,Vehicle Style_Convertible,Vehicle Style_Convertible SUV,Vehicle Style_Coupe,Vehicle Style_Crew Cab Pickup,Vehicle Style_Extended Cab Pickup,Vehicle Style_Passenger Minivan,Vehicle Style_Passenger Van,Vehicle Style_Regular Cab Pickup,Vehicle Style_Sedan,Vehicle Style_Wagon
2952,2017,132.0,4.0,4.0,35,27,2031,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4352,2008,210.0,6.0,4.0,19,13,5657,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3185,2017,404.0,6.0,4.0,26,18,1624,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8536,2010,300.0,6.0,4.0,22,16,204,0,0,0,...,0,0,0,0,0,0,0,0,1,0
7307,2016,248.0,6.0,4.0,28,19,2202,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9683,2008,617.0,8.0,2.0,16,12,617,0,0,0,...,1,0,0,0,0,0,0,0,0,0
88,1996,115.0,4.0,2.0,36,26,2009,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2137,2002,115.0,4.0,2.0,27,20,873,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2732,2017,402.0,8.0,4.0,26,18,617,0,0,0,...,0,0,0,0,0,0,0,0,1,0
488,2015,270.0,6.0,4.0,21,17,2031,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
y_test

2952     21665
4352     30015
3185     64395
8536     50450
7307     33500
         ...
9683    495000
88        2000
2137     23175
2732     74850
488      43620
Name: MSRP, Length: 2383, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC,LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
models = {
   # 'Linear_Regression'   : LinearRegression(),
    'Logistic_Regression' : LogisticRegression(),
   # 'Ridge'               : Ridge(),
   # 'Lasso'               : Lasso(),
   # 'Linear_SVC'          : LinearSVC(),
   # 'SVC'                 : SVC(),
   # 'Decision_Tree'       : DecisionTreeClassifier(),
   # 'Random_Forest'       : RandomForestClassifier(),
   # 'GNB'                 : GaussianNB()
}
for name,model in models.items():
    model.fit(X_train,y_train)
    print(name + ' Trainned')

In [ ]:
for name,model in models.items():
    print(name + ' Accuracy : {:2f}'.format(model.fit(X_test,y_test)))